# Generated by Django 5.2.3 on 2025-07-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('validated', models.BooleanField(default=False)),
                ('used_for_request', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
