# Generated by Django 5.2.3 on 2025-07-02 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clientprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='contact_function',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='external_link',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='institution_name',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='region',
        ),
        migrations.RemoveField(
            model_name='request',
            name='address',
        ),
        migrations.RemoveField(
            model_name='request',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='request',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='request',
            name='email',
        ),
        migrations.RemoveField(
            model_name='request',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='request',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='project_examples',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicetype'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
