# Generated by Django 5.2.3 on 2025-07-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlzEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plz', models.CharField(max_length=5)),
                ('ort', models.CharField(max_length=100)),
                ('bundesland', models.CharField(max_length=100)),
            ],
        ),
    ]
