# Generated by Django 5.2.3 on 2025-07-29 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plzentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundesland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Bundesland',
                'verbose_name_plural': 'Bundesländer',
            },
        ),
        migrations.CreateModel(
            name='PlzOrt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plz', models.CharField(max_length=5)),
                ('ort', models.CharField(max_length=100)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bundesland')),
            ],
            options={
                'verbose_name': 'PLZ + Ort',
                'verbose_name_plural': 'PLZ + Orte',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regionen', to='core.bundesland')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regionen',
                'unique_together': {('name', 'land')},
            },
        ),
        migrations.CreateModel(
            name='Strasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Straße',
                'verbose_name_plural': 'Straßen',
            },
        ),
        migrations.DeleteModel(
            name='PlzEntry',
        ),
        migrations.AddField(
            model_name='plzort',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region'),
        ),
        migrations.AddField(
            model_name='strasse',
            name='plz_ort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strassen', to='core.plzort'),
        ),
        migrations.AlterUniqueTogether(
            name='plzort',
            unique_together={('plz', 'ort')},
        ),
        migrations.AlterUniqueTogether(
            name='strasse',
            unique_together={('name', 'plz_ort')},
        ),
    ]
