# Generated by Django 5.2.3 on 2025-07-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bundesland_plzort_region_strasse_delete_plzentry_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plzort',
            unique_together={('plz', 'ort', 'region')},
        ),
    ]
