# Generated by Django 5.2.3 on 2025-07-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_plzort_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strasse',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='strasse',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='strasse',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
