# Generated by Django 5.2.3 on 2025-08-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_requestimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='requests', to='core.servicetype'),
        ),
    ]
