# Generated by Django 5.2.3 on 2025-08-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_request_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='category',
            field=models.CharField(default='Umweltfachplanung', max_length=100),
            preserve_default=False,
        ),
    ]
