# Generated by Django 5.2.3 on 2025-08-14 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_is_client_and_clean_current_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_provider',
        ),
    ]
