# Generated by Django 5.2.3 on 2025-09-16 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_request_extra_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofile',
            name='coverage_area',
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='coverage_regions',
            field=models.ManyToManyField(blank=True, related_name='providers', to='core.region'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='firma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='providers', to='core.servicetype'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='providerprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
